name: Get Reports

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Make Report Directory if needed
        run: mkdir -p Report

      - name: curl Qiita API
        run: |
          cd Report
          curl https://qiita.com/api/v2/items/cc28fc8a41b9932ecfb1/likes > test.txt
          cat test.txt
          echo test, and deploy your project.
